' Gambas module file

Public bazgi As Cvb
Public pak As Integer
Public kacino As Integer
Public yolac As String
Public dosya As String
Public cazgi As Czm
Public sazgi As Czm
Public renkcik As String
Public seksek As String
Public ucd As Float
Public tx As String
Public reskayit As Picture
Public myFile As File

Public Sub dxfkay(gf As String)

    Dim tt As Integer

    ilk.mesgul = 1
    If ilk.cezmi.Count > 99
        pak = ilk.cezmi.Count
    Else
        pak = 99
    End If
    ilk.ListBox10.Clear
    For Each cazgi In ilk.cezmi
        If cazgi.id > 0
            If ilk.ListBox10.Find(cazgi.blok) = -1 Then
                If cazgi.blok <> 0 Then
                    If cazgi.blok <> "" Then
                        ilk.ListBox10.Add(cazgi.blok)
                    End If
                End If
            End If
        End If
    Next
    If gf = ""
        myFile = Open System.User.Home &/ "yedek.dxf" For Create
        ilk.komyaz.Text = "Automatic record"
    Else If gf = "fea"
        myFile = Open System.User.Home &/ "z88y/z88x.dxf" For Create
    Else If gf = "fea2"
        myFile = Open System.User.Home &/ "z88y.dxf" For Create
    Else
        myFile = Open gf For Create
        ilk.komyaz.Text = "File is saving"
    End If
    sac
    For tt = 0 To ilk.ListBox10.Count - 1
        ilk.ListBox10.Index = tt
        Print #myFile, "BLOCK_RECORD"
        Print #myFile, "  5"
        pak = pak + 2
        Print #myFile, pak
        Print #myFile, "100"
        Print #myFile, "AcDbSymbolTableRecord"
        Print #myFile, "100"
        Print #myFile, "AcDbBlockTableRecord"
        Print #myFile, "  2"
        Print #myFile, ilk.ListBox10.Text
        Print #myFile, "340"
        Print #myFile, "0"
        Print #myFile, "  0"
    Next
    nbv
    For tt = 0 To ilk.ListBox10.Count - 1
        ilk.ListBox10.Index = tt
        Print #myFile, "BLOCK"
        Print #myFile, "  5"
        pak = pak + 2
        Print #myFile, pak
        Print #myFile, "100"
        Print #myFile, "AcDbEntity"
        Print #myFile, "  8"
        Print #myFile, "0"
        Print #myFile, "100"
        Print #myFile, "AcDbBlockBegin"
        Print #myFile, "  2"
        Print #myFile, ilk.ListBox10.Text
        Print #myFile, " 70"
        Print #myFile, "0"
        Print #myFile, " 10"
        Print #myFile, "0.0"
        Print #myFile, " 20"
        Print #myFile, "0.0"
        Print #myFile, " 30"
        Print #myFile, "0.0"
        Print #myFile, "  3"
        Print #myFile, ilk.ListBox10.Text
        Print #myFile, "  1"
        Print #myFile, ""
        Print #myFile, "  0"
        For Each cazgi In ilk.cezmi
            If cazgi.id > 0 Then
                If cazgi.blok = ilk.ListBox10.Text
                    If cazgi.komut = 25 Then cmb
                    If cazgi.komut = 20 Then arce
                    If cazgi.komut = 1 Then ciz
                End If
            End If
        Next
        Print #myFile, "ENDBLK"
        Print #myFile, "  5"
        pak = pak + 2
        Print #myFile, pak
        Print #myFile, "100"
        Print #myFile, "AcDbEntity"
        Print #myFile, "  8"
        Print #myFile, "0"
        Print #myFile, "100"
        Print #myFile, "AcDbBlockEnd"
        Print #myFile, "  0"
    Next
    Print #myFile, "ENDSEC"
    Print #myFile, "  0"
    Print #myFile, "SECTION"
    Print #myFile, "  2"
    Print #myFile, "ENTITIES"
    Print #myFile, "  0"
    For Each cazgi In ilk.cezmi
        If cazgi.id > 0 Then
            If cazgi.blok = 0 
                If cazgi.komut = 25 Then cmb
                If cazgi.komut = 20 Then arce
                If cazgi.komut = 1 Then ciz
            End If
            If cazgi.komut = 105 Or cazgi.komut = 100
                dolc
            End If
            If cazgi.komut = 60 Then yzi
            If cazgi.komut = 120 Then olc
            If cazgi.komut = 200 Then colc
            If cazgi.komut = 190 Then yolc
        End If
    Next
    For tt = 0 To ilk.ListBox10.Count - 1
        ilk.ListBox10.Index = tt
        Print #myFile, "INSERT"
        Print #myFile, "  5"
        pak = pak + 2
        Print #myFile, pak
        Print #myFile, "100"
        Print #myFile, "AcDbEntity"
        Print #myFile, "100"
        Print #myFile, "AcDbBlockReference"
        Print #myFile, "  8"
        Print #myFile, "0"
        Print #myFile, "  2"
        Print #myFile, ilk.ListBox10.Text
        Print #myFile, " 10"
        Print #myFile, "0.0"
        Print #myFile, " 20"
        Print #myFile, "0.0"
        Print #myFile, " 30"
        Print #myFile, "0.0"
        Print #myFile, "  0"
    Next
    son
    ilk.komyaz.Text = "Komut Satırı"
    If gf <> ""
        ilk.Text = "KediCAD2B " & " ~ " & ilk.kaci
        torba5.pasam(ilk.kaci)
        Close myFile
        If Exist(System.User.Home &/ ".KediCAD/Acilis/dosya.ulu") Then
            myFile = Open System.User.Home &/ ".KediCAD/Acilis/dosya.ulu" For Write
        Else
            myFile = Open System.User.Home &/ ".KediCAD/Acilis/dosya.ulu" For Create
        End If
        Seek #myFile, Lof(myFile)
        Print #myFile, ilk.kaci
        Close myFile
        ilk.mesgul = 0
    End If

    Return
       Catch
ilk.hatayaz("dxfkay  " & Error.Text, Error.Where & "--" & Error.code)
Return
End

Public kati As String

Sub ciz()

    Print #myFile, "LINE"
    Print #myFile, "  5"
    pak = pak + 2
    Print #myFile, pak
    Print #myFile, "100"
    Print #myFile, "AcDbEntity"
    Print #myFile, "100"
    Print #myFile, "AcDbLine"
    Print #myFile, "  8"
    katmanci
    Print #myFile, kati
    If cazgi.sekil <> 0 Or cazgi.sekil <> ""
        sekci(cazgi.sekil)
    Else
        seksek = "ByLayer"
    End If
    Print #myFile, "  6"
    Print #myFile, seksek
    renkli(cazgi.renk)
    Print #myFile, " 62"
    Print #myFile, renkcik
    Print #myFile, "370"
    Print #myFile, "-1"
    Print #myFile, " 10"
    ucd = cazgi.x1 - ilk.orix
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 20"
    ucd = -1 * cazgi.y1 + ilk.oriy
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, " 11"
    ucd = cazgi.x2 - ilk.orix
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 21"
    ucd = -1 * cazgi.y2 + ilk.oriy
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 31"
    Print #myFile, "0.0"
    Print #myFile, "  0"
    Return
       Catch
ilk.hatayaz("ciz " & Error.Text, Error.Where & "--" & Error.code)
Return
End

Sub cmb()

    Print #myFile, "CIRCLE"
    Print #myFile, "  5"
    pak = pak + 2
    Print #myFile, pak
    Print #myFile, "100"
    Print #myFile, "AcDbEntity"
    Print #myFile, "  8"
    katmanci
    Print #myFile, kati
    If cazgi.sekil <> 0 Or cazgi.sekil <> ""
        sekci(cazgi.sekil)
    Else
        seksek = "ByLayer"
    End If
    Print #myFile, "  6"
    Print #myFile, seksek
    renkli(cazgi.renk)
    Print #myFile, " 62"
    Print #myFile, renkcik
    Print #myFile, "100"
    Print #myFile, "AcDbCircle"
    Print #myFile, " 10"
    ucd = cazgi.x1 - ilk.orix
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 20"
    ucd = -1 * cazgi.y1 + ilk.oriy
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, " 40"
    ucd = cazgi.yaricap
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, "  0"
    Return
       Catch
ilk.hatayaz("cmb " & Error.Text, Error.Where & "--" & Error.code)
Return
End

Sub arce()

    Print #myFile, "ARC"
    Print #myFile, "  5"
    pak = pak + 2
    Print #myFile, pak
    Print #myFile, "100"
    Print #myFile, "AcDbEntity"
    Print #myFile, "  8"
    katmanci
    Print #myFile, kati
    If cazgi.sekil <> 0 Or cazgi.sekil <> ""
        sekci(cazgi.sekil)
    Else
        seksek = "ByLayer"
    End If
    Print #myFile, "  6"
    Print #myFile, seksek
    renkli(cazgi.renk)
    Print #myFile, " 62"
    Print #myFile, renkcik
    Print #myFile, "100"
    Print #myFile, "AcDbCircle"
    Print #myFile, " 10"
    ucd = cazgi.x1 - ilk.orix
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 20"
    ucd = -1 * cazgi.y1 + ilk.oriy
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, " 40"
    ucd = cazgi.yaricap
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, "100"
    Print #myFile, "AcDbArc"
    Print #myFile, " 50"
    ucd = cazgi.r
    ucd = Deg(ucd)
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 51"
    ucd = cazgi.teta
    ucd = Deg(ucd)
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, "  0"
    Return
       Catch
ilk.hatayaz("arce " & Error.Text, Error.Where & "--" & Error.code)
Return
End

Sub yzi()

    Dim fv As String

    fv = cazgi.yazi
    Print #myFile, "TEXT"
    Print #myFile, "  5"
    pak = pak + 2
    Print #myFile, pak
    Print #myFile, "100"
    Print #myFile, "AcDbEntity"
    Print #myFile, "100"
    Print #myFile, "AcDbText"
    Print #myFile, "  8"
    katmanci
    Print #myFile, kati
    renkli(cazgi.renk)
    Print #myFile, " 62"
    Print #myFile, renkcik
    Print #myFile, "370"
    Print #myFile, "-1"
    Print #myFile, " 10"
    ucd = cazgi.x1 - ilk.orix
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 20"
    ucd = -1 * cazgi.y1 - (cazgi.x6 / 2) + ilk.oriy
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, " 40"
    ucd = cazgi.x6
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, "  1"
    Print #myFile, cazgi.yazi
    Print #myFile, "100"
    Print #myFile, "AcDbText"
    Print #myFile, "  0"
    Return
       Catch
ilk.hatayaz("yzi " & Error.Text, Error.Where & "--" & Error.code)
Return
End

Sub dolc()          '  Dik ölçü  100    105

    Print #myFile, "DIMENSION"
    Print #myFile, "  5"
    pak = pak + 2
    Print #myFile, pak
    Print #myFile, "100"
    Print #myFile, "AcDbEntity"
    Print #myFile, "  8"
    katmanci
    Print #myFile, kati
    If cazgi.sekil <> 0 Or cazgi.sekil <> ""
        sekci(cazgi.sekil)
    Else
        seksek = "ByLayer"
    End If
    Print #myFile, "  6"
    Print #myFile, seksek
    renkli(cazgi.renk)
    Print #myFile, " 62"
    Print #myFile, renkcik
    Print #myFile, "370"
    Print #myFile, "-1"
    Print #myFile, "  6"
    Print #myFile, "ByLayer"
    Print #myFile, "100"
    Print #myFile, "AcDbDimension"
    Print #myFile, " 10"
    ucd = cazgi.x4 - ilk.orix
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 20"
    ucd = -1 * cazgi.y4 + ilk.oriy
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, " 11"
    ucd = cazgi.yazix - ilk.orix
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 21"
    ucd = -1 * cazgi.yaziy + ilk.oriy
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 31"
    Print #myFile, "0.0"
    Print #myFile, " 70"
    Print #myFile, "0"
    Print #myFile, " 71"
    Print #myFile, "5"
    Print #myFile, " 72"
    Print #myFile, "1"
    Print #myFile, " 41"
    Print #myFile, "1.0"
    Print #myFile, " 42"
    Print #myFile, "0.0"
    Print #myFile, "  1"
    Print #myFile, ""
    Print #myFile, "  3"
    Print #myFile, "Standard"
    Print #myFile, "100"
    Print #myFile, "AcDbAlignedDimension"
    Print #myFile, " 13"
    ucd = cazgi.x2 - ilk.orix
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 23"
    ucd = -1 * cazgi.y2 + ilk.oriy
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 33"
    Print #myFile, "0.0"
    Print #myFile, " 14"
    ucd = cazgi.x1 - ilk.orix
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 24"
    ucd = -1 * cazgi.y1 + ilk.oriy
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 34"
    Print #myFile, "0.0"
    Print #myFile, " 50"
    If cazgi.komut = 100
        Print #myFile, "0.0"
    Else
        Print #myFile, "90.0"
    End If
    Print #myFile, "100"
    Print #myFile, "AcDbRotatedDimension"
    Print #myFile, "  0"
    Return
       Catch
ilk.hatayaz("dolc " & Error.Text, Error.Where & "--" & Error.code)
Return
End

Sub olc()         ' 120 Eğik ölçü

    Print #myFile, "DIMENSION"
    Print #myFile, "  5"
    pak = pak + 2
    Print #myFile, pak
    Print #myFile, "100"
    Print #myFile, "AcDbEntity"
    Print #myFile, "  8"
    katmanci
    Print #myFile, kati
    If cazgi.sekil <> 0 Or cazgi.sekil <> ""
        sekci(cazgi.sekil)
    Else
        seksek = "ByLayer"
    End If
    Print #myFile, "  6"
    Print #myFile, seksek
    renkli(cazgi.renk)
    Print #myFile, " 62"
    Print #myFile, renkcik
    Print #myFile, "370"
    Print #myFile, "-1"
    Print #myFile, "  6"
    Print #myFile, "ByLayer"
    Print #myFile, "100"
    Print #myFile, "AcDbDimension"
    Print #myFile, " 10"
    ucd = cazgi.x5 - ilk.orix
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 20"
    ucd = -1 * cazgi.y5 + ilk.oriy
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, " 11"
    ucd = cazgi.yazix - ilk.orix
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 21"
    ucd = -1 * cazgi.yaziy + ilk.oriy
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 31"
    Print #myFile, "0.0"
    Print #myFile, " 70"
    Print #myFile, "1"
    Print #myFile, " 71"
    Print #myFile, "5"
    Print #myFile, " 72"
    Print #myFile, "0"
    Print #myFile, " 41"
    Print #myFile, "1.0"
    Print #myFile, " 42"
    Print #myFile, "0.0"
    Print #myFile, "  1"
    Print #myFile, ""
    Print #myFile, "  3"
    Print #myFile, "Standard"
    Print #myFile, "100"
    Print #myFile, "AcDbAlignedDimension"
    Print #myFile, " 13"
    ucd = cazgi.x1 - ilk.orix
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 23"
    ucd = -1 * cazgi.y1 + ilk.oriy
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 33"
    Print #myFile, "0.0"
    Print #myFile, " 14"
    ucd = cazgi.x2 - ilk.orix
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 24"
    ucd = -1 * cazgi.y2 + ilk.oriy
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 34"
    Print #myFile, "0.0"
    Print #myFile, "  0"
    Return
       Catch
ilk.hatayaz("olc " & Error.Text, Error.Where & "--" & Error.code)
Return
End

Sub colc()

    Print #myFile, "DIMENSION"
    Print #myFile, "  5"
    pak = pak + 2
    Print #myFile, pak
    Print #myFile, "100"
    Print #myFile, "AcDbEntity"
    Print #myFile, "  8"
    katmanci
    Print #myFile, kati
    If cazgi.sekil <> 0 Or cazgi.sekil <> ""
        sekci(cazgi.sekil)
    Else
        seksek = "ByLayer"
    End If
    Print #myFile, "  6"
    Print #myFile, seksek
    renkli(cazgi.renk)
    Print #myFile, " 62"
    Print #myFile, renkcik
    Print #myFile, "100"
    Print #myFile, "AcDbDimension"
    Print #myFile, " 10"
    ucd = cazgi.x4 - ilk.orix
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 20"
    ucd = -1 * cazgi.y4 + ilk.oriy
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, " 11"
    ucd = cazgi.yazix - ilk.orix
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 21"
    ucd = -1 * cazgi.yaziy + ilk.oriy
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 31"
    Print #myFile, "0.0"
    Print #myFile, " 70"
    Print #myFile, "3"
    Print #myFile, " 71"
    Print #myFile, "     5"
    Print #myFile, " 72"
    Print #myFile, "     1"
    Print #myFile, " 41"
    Print #myFile, "1.0"
    Print #myFile, " 42"
    Print #myFile, "0.0"
    Print #myFile, "  1"
    Print #myFile, ""
    Print #myFile, "  3"
    Print #myFile, "Standard"
    Print #myFile, "100"
    Print #myFile, "AcDbDiametricDimension"
    Print #myFile, " 15"
    ucd = cazgi.x5 - ilk.orix
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 25"
    ucd = -1 * cazgi.y5 + ilk.oriy
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 35"
    Print #myFile, "0.0"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  0"
    Return
       Catch
ilk.hatayaz("colc " & Error.Text, Error.Where & "--" & Error.code)
Return
End

Sub yolc()

    Print #myFile, "DIMENSION"
    Print #myFile, "  5"
    pak = pak + 2
    Print #myFile, pak
    Print #myFile, "100"
    Print #myFile, "AcDbEntity"
    Print #myFile, "  8"
    katmanci
    Print #myFile, kati
    If cazgi.sekil <> 0 Or cazgi.sekil <> ""
        sekci(cazgi.sekil)
    Else
        seksek = "ByLayer"
    End If
    Print #myFile, "  6"
    Print #myFile, seksek
    renkli(cazgi.renk)
    Print #myFile, " 62"
    Print #myFile, renkcik
    Print #myFile, "100"
    Print #myFile, "AcDbDimension"
    Print #myFile, " 10"
    ucd = cazgi.x1 - ilk.orix
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 20"
    ucd = -1 * cazgi.y1 + ilk.oriy
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, " 11"
    ucd = cazgi.yazix - ilk.orix
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 21"
    ucd = -1 * cazgi.yaziy + ilk.oriy
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 31"
    Print #myFile, "0.0"
    Print #myFile, " 70"
    Print #myFile, "4"
    Print #myFile, " 71"
    Print #myFile, "5"
    Print #myFile, " 72"
    Print #myFile, "0"
    Print #myFile, " 41"
    Print #myFile, "1.0"
    Print #myFile, " 42"
    Print #myFile, "0.0"
    Print #myFile, "  1"
    Print #myFile, ""
    Print #myFile, "  3"
    Print #myFile, "Standard"
    Print #myFile, "100"
    Print #myFile, "AcDbRadialDimension"
    Print #myFile, " 15"
    ucd = cazgi.x4 - ilk.orix
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 25"
    ucd = -1 * cazgi.y4 + ilk.oriy
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 35"
    Print #myFile, "0.0"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  0"
    Return
       Catch
ilk.hatayaz("yolc " & Error.Text, Error.Where & "--" & Error.code)
Return
End

Sub ketmen()

    For Each bazgi In ilk.bezmi
        If bazgi.ad <> "Defpoints"
            Print #myFile, "LAYER"
            Print #myFile, "  5"
            pak = pak + 2
            Print #myFile, pak
            Print #myFile, "330"
            Print #myFile, "2"
            Print #myFile, "100"
            Print #myFile, "AcDbSymbolTableRecord"
            Print #myFile, "100"
            Print #myFile, "AcDbLayerTableRecord"
            Print #myFile, "  2"
            Print #myFile, bazgi.ad
            Print #myFile, " 70"
            If bazgi.gor <> 0
                Print #myFile, "     1"
            Else
                Print #myFile, "     0"
            End If
            Print #myFile, " 62"
            renkli(bazgi.renk)
            Print #myFile, renkcik
            If bazgi.tip <> 0 Or bazgi.tip <> ""
                sekci(bazgi.tip)
            Else
                seksek = "ByLayer"
            End If
            Print #myFile, "  6"
            Print #myFile, seksek
            Print #myFile, "370"
            Print #myFile, "    -3"
            Print #myFile, "390"
            Print #myFile, "F"
            Print #myFile, "  0"
        End If
    Next
    Return
       Catch
ilk.hatayaz("ketmen " & Error.Text, Error.Where & "--" & Error.code)
Return
End

Sub renkli(pnb As Integer)

    If pnb = "16711680" Then
        renkcik = "1" 'kırmızı
    Else If pnb = "16776960" Then
        renkcik = "2"      'sarı
    Else If pnb = "65280" Then
        renkcik = "3"     'yeşil
    Else If pnb = "65535" Then
        renkcik = "4"   'cyan
    Else If pnb = "255" Then
        renkcik = "5"   'mavi
    Else If pnb = "16711935" Then
        renkcik = "6"      'mor
    Else If pnb = "16777215" Then
        renkcik = "7"      'beyaz
    Else If pnb = "10526884" Then
        renkcik = "8"     'koyu gri
    Else If pnb = "12632256" Then
        renkcik = "9"     'açık  gri
    Else If pnb = "11141120" Then
        renkcik = "12"
    Else If pnb = "21760" Then
        renkcik = "96"
    Else If pnb = "11162880" Then
        renkcik = "32"
    Else If pnb = "43520" Then
        renkcik = "92"
    Else If pnb = "11184640" Then
        renkcik = "52"
    Else If pnb = "11206400" Then
        renkcik = "60"
    Else If pnb = "127" Then
        renkcik = "174"
    Else If pnb = "11141247" Then
        renkcik = "222"
    Else If pnb = "21887" Then
        renkcik = "144"
    Else If pnb = "11163007" Then
        renkcik = "233"
    Else If pnb = "43647" Then
        renkcik = "122"
    Else If pnb = "11184767" Then
        renkcik = "53"
    Else If pnb = "65407" Then
        renkcik = "110"
    Else If pnb = "11206527" Then
        renkcik = "81"
    Else If pnb = "11141375" Then
        renkcik = "200"
    Else If pnb = "22015" Then
        renkcik = "160"
    Else If pnb = "11163135" Then
        renkcik = "181"
    Else If pnb = "43775" Then
        renkcik = "140"
    Else If pnb = "11184895" Then
        renkcik = "370"
    Else If pnb = "65535" Then
        renkcik = "4"
    Else If pnb = "11206655" Then
        renkcik = "131"
    Else If pnb = "5570560" Then
        renkcik = "16"
    Else If pnb = "16711680" Then
        renkcik = "1"
    Else If pnb = "5592320" Then
        renkcik = "56"
    Else If pnb = "16733440" Then
        renkcik = "20"
    Else If pnb = "5614080" Then
        renkcik = "72"
    Else If pnb = "16755200" Then
        renkcik = "40"
    Else If pnb = "5635840" Then
        renkcik = "80"
    Else If pnb = "16776960" Then
        renkcik = "2"
    Else If pnb = "5570687" Then
        renkcik = "204"
    Else If pnb = "16711807" Then
        renkcik = "230"
    Else If pnb = "5592447" Then
        renkcik = "165"
    Else If pnb = "16733567" Then
        renkcik = "11"
    Else If pnb = "5614207" Then
        renkcik = "113"
    Else If pnb = "16755327" Then
        renkcik = "21"
    Else If pnb = "5635967" Then
        renkcik = "91"
    Else If pnb = "16777087" Then
        renkcik = "51"
    Else If pnb = "5570815" Then
        renkcik = "180"
    Else If pnb = "16711935" Then
        renkcik = "6"
    Else If pnb = "5592575" Then
        renkcik = "171"
    Else If pnb = "16733695" Then
        renkcik = "211"
    Else If pnb = "5614335" Then
        renkcik = "161"
    Else If pnb = "16755455" Then
        renkcik = "211"
    Else If pnb = "5636095" Then
        renkcik = "131"
    Else
        renkcik = "7"
    End If
    Return
       Catch
          renkcik = "7" 
ilk.hatayaz("diz " & Error.Text, Error.Where & "--" & Error.code)
Return
End

Public Sub katmanci()

    If cazgi.katman <> "" Then
        kati = cazgi.katman
    Else
        kati = "0"
    Endif

    Return

End

Public Sub sekci(bnb As Integer)

    If bnb = 2
        seksek = "DASHED2"
    Else If bnb = 4 Then
        seksek = "DOT"
    Else If bnb = 5 Then
        seksek = "CENTER"
    Else If bnb = 6 Then
        seksek = "DIVIDE"
    Else If bnb = 3 Then
        seksek = "DASHED"
    Else
        seksek = "CONTINUOUS"
    End If
    Return
Catch
    ilk.hatayaz("sekci " & Error.Text, Error.Where & "--" & Error.code)
    seksek = "ByLayer"
    Return

End

Sub uyuz(gelen As String)

    Dim elt As String[]
    Dim sb As String
    Dim x As Integer

    elt = Split(gelen, ",")
    For Each sb In elt
        If x = 0 Then tx = sb
        If x = 1 Then tx = tx & "." & sb
        tx = Trim$(tx)
        x = x + 1
    Next
    Return
Catch
    ilk.hatayaz("uyuz " & Error.Text, Error.Where & "--" & Error.code)
Return
End

Sub sac()

    Print #myFile, "999"
    Print #myFile, "dxflib 2.0.4.8"
    Print #myFile, "  0"
    Print #myFile, "SECTION"
    Print #myFile, "  2"
    Print #myFile, "HEADER"
    Print #myFile, "  9"
    Print #myFile, "$ACADVER"
    Print #myFile, "  1"
    Print #myFile, "AC1015"
    Print #myFile, "  9"
    Print #myFile, "$HANDSEED"
    Print #myFile, "  5"
    Print #myFile, "FFFF"
    Print #myFile, "  9"
    Print #myFile, "$USERR4"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$DIMTDEC"
    Print #myFile, " 70"
    Print #myFile, "2"
    Print #myFile, "  9"
    Print #myFile, "$DIMTAD"
    Print #myFile, " 70"
    Print #myFile, "1"
    Print #myFile, "  9"
    Print #myFile, "$CMLSTYLE"
    Print #myFile, "  2"
    Print #myFile, "Standard"
    Print #myFile, "  9"
    Print #myFile, "$VISRETAIN"
    Print #myFile, " 70"
    Print #myFile, "1"
    Print #myFile, "  9"
    Print #myFile, "$TILEMODE"
    Print #myFile, " 70"
    Print #myFile, "1"
    Print #myFile, "  9"
    Print #myFile, "$SHADEDIF"
    Print #myFile, " 70"
    Print #myFile, "70"
    Print #myFile, "  9"
    Print #myFile, "$USERR5"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$UCSYDIR"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "1.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$CHAMFERA"
    Print #myFile, " 40"
    Print #myFile, "10.0"
    Print #myFile, "  9"
    Print #myFile, "$MENU"
    Print #myFile, "  1"
    Print #myFile, "."
    Print #myFile, "  9"
    Print #myFile, "$DIMALTZ"
    Print #myFile, " 70"
    Print #myFile, "0"
    Print #myFile, "  9"
    Print #myFile, "$CLAYER"
    Print #myFile, "  8"
    Print #myFile, "0"
    Print #myFile, "  9"
    Print #myFile, "$OLESTARTUP"
    Print #myFile, "290"
    Print #myFile, "0"
    Print #myFile, "  9"
    Print #myFile, "$UCSXDIR"
    Print #myFile, " 10"
    Print #myFile, "1.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$CHAMFERB"
    Print #myFile, " 40"
    Print #myFile, "10.0"
    Print #myFile, "  9"
    Print #myFile, "$DIMADEC"
    Print #myFile, " 70"
    Print #myFile, "0"
    Print #myFile, "  9"
    Print #myFile, "$DIMUPT"
    Print #myFile, " 70"
    Print #myFile, "0"
    Print #myFile, "  9"
    Print #myFile, "$DIMASZ"
    Print #myFile, " 40"
    Print #myFile, "2.5"
    Print #myFile, "  9"
    Print #myFile, "$TRACEWID"
    Print #myFile, " 40"
    Print #myFile, "1.0"
    Print #myFile, "  9"
    Print #myFile, "$REGENMODE"
    Print #myFile, " 70"
    Print #myFile, "1"
    Print #myFile, "  9"
    Print #myFile, "$ORTHOMODE"
    Print #myFile, " 70"
    Print #myFile, "0"
    Print #myFile, "  9"
    Print #myFile, "$EXTMIN"
    Print #myFile, " 10"
    ucd = torba6.basx - ilk.orix
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 20"
    ucd = -1 * torba6.basy + ilk.oriy
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$ENDCAPS"
    Print #myFile, "280"
    Print #myFile, "0"
    Print #myFile, "  9"
    Print #myFile, "$MEASUREMENT"
    Print #myFile, " 70"
    Print #myFile, "1"
    Print #myFile, "  9"
    Print #myFile, "$CMLJUST"
    Print #myFile, " 70"
    Print #myFile, "0"
    Print #myFile, "  9"
    Print #myFile, "$PUCSYDIR"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "1.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$ANGBASE"
    Print #myFile, " 50"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$USRTIMER"
    Print #myFile, " 70"
    Print #myFile, "1"
    Print #myFile, "  9"
    Print #myFile, "$CHAMFERC"
    Print #myFile, " 40"
    Print #myFile, "20.0"
    Print #myFile, "  9"
    Print #myFile, "$SKETCHINC"
    Print #myFile, " 40"
    Print #myFile, "1.0"
    Print #myFile, "  9"
    Print #myFile, "$DIMGAP"
    Print #myFile, " 40"
    Print #myFile, "0.625"
    Print #myFile, "  9"
    Print #myFile, "$DIMTFAC"
    Print #myFile, " 40"
    Print #myFile, "1.0"
    Print #myFile, "  9"
    Print #myFile, "$DIMSAH"
    Print #myFile, " 70"
    Print #myFile, "0"
    Print #myFile, "  9"
    Print #myFile, "$DIMALT"
    Print #myFile, " 70"
    Print #myFile, "0"
    Print #myFile, "  9"
    Print #myFile, "$DIMSHO"
    Print #myFile, " 70"
    Print #myFile, "1"
    Print #myFile, "  9"
    Print #myFile, "$VERSIONGUID"
    Print #myFile, "  2"
    Print #myFile, "{32691AAC-1F59-11DD-3286-0002449A8F44}"
    Print #myFile, "  9"
    Print #myFile, "$LWDISPLAY"
    Print #myFile, "290"
    Print #myFile, "0"
    Print #myFile, "  9"
    Print #myFile, "$PUCSXDIR"
    Print #myFile, " 10"
    Print #myFile, "1.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$SURFTYPE"
    Print #myFile, " 70"
    Print #myFile, "6"
    Print #myFile, "  9"
    Print #myFile, "$SPLFRAME"
    Print #myFile, " 70"
    Print #myFile, "0"
    Print #myFile, "  9"
    Print #myFile, "$CHAMFERD"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$DIMALTRND"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$DIMALTTD"
    Print #myFile, " 70"
    Print #myFile, "3"
    Print #myFile, "  9"
    Print #myFile, "$DIMTSZ"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$LIMMIN"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$CELWEIGHT"
    Print #myFile, "370"
    Print #myFile, "-1"
    Print #myFile, "  9"
    Print #myFile, "$SURFTAB1"
    Print #myFile, " 70"
    Print #myFile, "6"
    Print #myFile, "  9"
    Print #myFile, "$SPLINESEGS"
    Print #myFile, " 70"
    Print #myFile, "8"
    Print #myFile, "  9"
    Print #myFile, "$AUPREC"
    Print #myFile, " 70"
    Print #myFile, "0"
    Print #myFile, "  9"
    Print #myFile, "$LUNITS"
    Print #myFile, " 70"
    Print #myFile, "2"
    Print #myFile, "  9"
    Print #myFile, "$DWGCODEPAGE"
    Print #myFile, "  3"
    Print #myFile, "ANSI_1254"
    Print #myFile, "  9"
    Print #myFile, "$PSTYLEMODE"
    Print #myFile, "290"
    Print #myFile, "1"
    Print #myFile, "  9"
    Print #myFile, "$UNITMODE"
    Print #myFile, " 70"
    Print #myFile, "0"
    Print #myFile, "  9"
    Print #myFile, "$USERI1"
    Print #myFile, " 70"
    Print #myFile, "0"
    Print #myFile, "  9"
    Print #myFile, "$UCSORTHOVIEW"
    Print #myFile, " 70"
    Print #myFile, "0"
    Print #myFile, "  9"
    Print #myFile, "$SURFTAB2"
    Print #myFile, " 70"
    Print #myFile, "6"
    Print #myFile, "  9"
    Print #myFile, "$TDUUPDATE"
    Print #myFile, " 40"
    Print #myFile, "2454598.5368625922128558"
    Print #myFile, "  9"
    Print #myFile, "$TDUCREATE"
    Print #myFile, " 40"
    Print #myFile, "2454598.5160534367896616"
    Print #myFile, "  9"
    Print #myFile, "$SKPOLY"
    Print #myFile, " 70"
    Print #myFile, "0"
    Print #myFile, "  9"
    Print #myFile, "$ELEVATION"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$DIMDSEP"
    Print #myFile, " 70"
    Print #myFile, "44"
    Print #myFile, "  9"
    Print #myFile, "$DIMCEN"
    Print #myFile, " 40"
    Print #myFile, "2.5"
    Print #myFile, "  9"
    Print #myFile, "$DIMRND"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$INSBASE"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$INSUNITS"
    Print #myFile, " 70"
    Print #myFile, "4"
    Print #myFile, "  9"
    Print #myFile, "$USERI2"
    Print #myFile, " 70"
    Print #myFile, "0"
    Print #myFile, "  9"
    Print #myFile, "$UCSORGRIGHT"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$UCSORG"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$PELEVATION"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$DIMEXO"
    Print #myFile, " 40"
    Print #myFile, "0.625"
    Print #myFile, "  9"
    Print #myFile, "$TEXTSIZE"
    Print #myFile, " 40"
    Print #myFile, "2.5"
    Print #myFile, "  9"
    Print #myFile, "$FILLMODE"
    Print #myFile, " 70"
    Print #myFile, "1"
    Print #myFile, "  9"
    Print #myFile, "$EXTMAX"
    Print #myFile, " 10"
    ucd = torba6.sonx - ilk.orix
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 20"
    ucd = -1 * torba6.sony + ilk.oriy
    uyuz(ucd)
    Print #myFile, tx
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$LIMMAX"
    Print #myFile, " 10"
    Print #myFile, "420.0"
    Print #myFile, " 20"
    Print #myFile, "297.0"
    Print #myFile, "  9"
    Print #myFile, "$ORTHOMODE"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$REGENMODE"
    Print #myFile, " 70"
    Print #myFile, "     1"
    Print #myFile, "  9"
    Print #myFile, "$FILLMODE"
    Print #myFile, " 70"
    Print #myFile, "     1"
    Print #myFile, "  9"
    Print #myFile, "$QTEXTMODE"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$MIRRTEXT"
    Print #myFile, " 70"
    Print #myFile, "     1"
    Print #myFile, "  9"
    Print #myFile, "$LTSCALE"
    Print #myFile, " 40"
    Print #myFile, "1.0"
    Print #myFile, "  9"
    Print #myFile, "$ATTMODE"
    Print #myFile, " 70"
    Print #myFile, "     1"
    Print #myFile, "  9"
    Print #myFile, "$TEXTSIZE"
    Print #myFile, " 40"
    Print #myFile, "2.5"
    Print #myFile, "  9"
    Print #myFile, "$TRACEWID"
    Print #myFile, " 40"
    Print #myFile, "1.0"
    Print #myFile, "  9"
    Print #myFile, "$TEXTSTYLE"
    Print #myFile, "  7"
    Print #myFile, "Standard"
    Print #myFile, "  9"
    Print #myFile, "$CLAYER"
    Print #myFile, "  8"
    Print #myFile, "0"
    Print #myFile, "  9"
    Print #myFile, "$CELTYPE"
    Print #myFile, "  6"
    Print #myFile, "ByLayer"
    Print #myFile, "  9"
    Print #myFile, "$CECOLOR"
    Print #myFile, " 62"
    Print #myFile, "   256"
    Print #myFile, "  9"
    Print #myFile, "$CELTSCALE"
    Print #myFile, " 40"
    Print #myFile, "1.0"
    Print #myFile, "  9"
    Print #myFile, "$DISPSILH"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMSCALE"
    Print #myFile, " 40"
    Print #myFile, "1.0"
    Print #myFile, "  9"
    Print #myFile, "$DIMASZ"
    Print #myFile, " 40"
    Print #myFile, "2.5"
    Print #myFile, "  9"
    Print #myFile, "$DIMEXO"
    Print #myFile, " 40"
    Print #myFile, "0.625"
    Print #myFile, "  9"
    Print #myFile, "$DIMDLI"
    Print #myFile, " 40"
    Print #myFile, "3.75"
    Print #myFile, "  9"
    Print #myFile, "$DIMRND"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$DIMDLE"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$DIMEXE"
    Print #myFile, " 40"
    Print #myFile, "1.25"
    Print #myFile, "  9"
    Print #myFile, "$DIMTP"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$DIMTM"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$DIMTXT"
    Print #myFile, " 40"
    Print #myFile, "2.5"
    Print #myFile, "  9"
    Print #myFile, "$DIMCEN"
    Print #myFile, " 40"
    Print #myFile, "2.5"
    Print #myFile, "  9"
    Print #myFile, "$DIMTSZ"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$DIMTOL"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMLIM"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMTIH"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMTOH"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMSE1"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMSE2"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMTAD"
    Print #myFile, " 70"
    Print #myFile, "     1"
    Print #myFile, "  9"
    Print #myFile, "$DIMZIN"
    Print #myFile, " 70"
    Print #myFile, "     8"
    Print #myFile, "  9"
    Print #myFile, "$DIMBLK"
    Print #myFile, "  1"
    Print #myFile, ""
    Print #myFile, "  9"
    Print #myFile, "$DIMASO"
    Print #myFile, " 70"
    Print #myFile, "     1"
    Print #myFile, "  9"
    Print #myFile, "$DIMSHO"
    Print #myFile, " 70"
    Print #myFile, "     1"
    Print #myFile, "  9"
    Print #myFile, "$DIMPOST"
    Print #myFile, "  1"
    Print #myFile, ""
    Print #myFile, "  9"
    Print #myFile, "$DIMAPOST"
    Print #myFile, "  1"
    Print #myFile, ""
    Print #myFile, "  9"
    Print #myFile, "$DIMALT"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMALTD"
    Print #myFile, " 70"
    Print #myFile, "     3"
    Print #myFile, "  9"
    Print #myFile, "$DIMALTF"
    Print #myFile, " 40"
    Print #myFile, "0.03937007874016"
    Print #myFile, "  9"
    Print #myFile, "$DIMLFAC"
    Print #myFile, " 40"
    Print #myFile, "1.0"
    Print #myFile, "  9"
    Print #myFile, "$DIMTOFL"
    Print #myFile, " 70"
    Print #myFile, "     1"
    Print #myFile, "  9"
    Print #myFile, "$DIMTVP"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$DIMTIX"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMSOXD"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMSAH"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMBLK1"
    Print #myFile, "  1"
    Print #myFile, ""
    Print #myFile, "  9"
    Print #myFile, "$DIMBLK2"
    Print #myFile, "  1"
    Print #myFile, ""
    Print #myFile, "  9"
    Print #myFile, "$DIMSTYLE"
    Print #myFile, "  2"
    Print #myFile, "ISO-25"
    Print #myFile, "  9"
    Print #myFile, "$DIMCLRD"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMCLRE"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMCLRT"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMTFAC"
    Print #myFile, " 40"
    Print #myFile, "1.0"
    Print #myFile, "  9"
    Print #myFile, "$DIMGAP"
    Print #myFile, " 40"
    Print #myFile, "0.625"
    Print #myFile, "  9"
    Print #myFile, "$DIMJUST"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMSD1"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMSD2"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMTOLJ"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMTZIN"
    Print #myFile, " 70"
    Print #myFile, "     8"
    Print #myFile, "  9"
    Print #myFile, "$DIMALTZ"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMALTTZ"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMUPT"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMDEC"
    Print #myFile, " 70"
    Print #myFile, "     2"
    Print #myFile, "  9"
    Print #myFile, "$DIMTDEC"
    Print #myFile, " 70"
    Print #myFile, "     2"
    Print #myFile, "  9"
    Print #myFile, "$DIMALTU"
    Print #myFile, " 70"
    Print #myFile, "     2"
    Print #myFile, "  9"
    Print #myFile, "$DIMALTTD"
    Print #myFile, " 70"
    Print #myFile, "     3"
    Print #myFile, "  9"
    Print #myFile, "$DIMTXSTY"
    Print #myFile, "  7"
    Print #myFile, "Standard"
    Print #myFile, "  9"
    Print #myFile, "$DIMAUNIT"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMADEC"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMALTRND"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$DIMAZIN"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMDSEP"
    Print #myFile, " 70"
    Print #myFile, "    44"
    Print #myFile, "  9"
    Print #myFile, "$DIMATFIT"
    Print #myFile, " 70"
    Print #myFile, "     3"
    Print #myFile, "  9"
    Print #myFile, "$DIMFRAC"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$DIMLDRBLK"
    Print #myFile, "  1"
    Print #myFile, ""
    Print #myFile, "  9"
    Print #myFile, "$DIMLUNIT"
    Print #myFile, " 70"
    Print #myFile, "     2"
    Print #myFile, "  9"
    Print #myFile, "$DIMLWD"
    Print #myFile, " 70"
    Print #myFile, "    -2"
    Print #myFile, "  9"
    Print #myFile, "$DIMLWE"
    Print #myFile, " 70"
    Print #myFile, "    -2"
    Print #myFile, "  9"
    Print #myFile, "$DIMTMOVE"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$LUNITS"
    Print #myFile, " 70"
    Print #myFile, "     2"
    Print #myFile, "  9"
    Print #myFile, "$LUPREC"
    Print #myFile, " 70"
    Print #myFile, "     4"
    Print #myFile, "  9"
    Print #myFile, "$SKETCHINC"
    Print #myFile, " 40"
    Print #myFile, "1.0"
    Print #myFile, "  9"
    Print #myFile, "$FILLETRAD"
    Print #myFile, " 40"
    Print #myFile, "10.0"
    Print #myFile, "  9"
    Print #myFile, "$AUNITS"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$AUPREC"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$MENU"
    Print #myFile, "  1"
    Print #myFile, "."
    Print #myFile, "  9"
    Print #myFile, "$ELEVATION"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$PELEVATION"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$THICKNESS"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$LIMCHECK"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$CHAMFERA"
    Print #myFile, " 40"
    Print #myFile, "10.0"
    Print #myFile, "  9"
    Print #myFile, "$CHAMFERB"
    Print #myFile, " 40"
    Print #myFile, "10.0"
    Print #myFile, "  9"
    Print #myFile, "$CHAMFERC"
    Print #myFile, " 40"
    Print #myFile, "20.0"
    Print #myFile, "  9"
    Print #myFile, "$CHAMFERD"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$SKPOLY"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$TDCREATE"
    Print #myFile, " 40"
    Print #myFile, "2454598.641053438"
    Print #myFile, "  9"
    Print #myFile, "$TDUCREATE"
    Print #myFile, " 40"
    Print #myFile, "2454598.516053437"
    Print #myFile, "  9"
    Print #myFile, "$TDUPDATE"
    Print #myFile, " 40"
    Print #myFile, "2454598.661862593"
    Print #myFile, "  9"
    Print #myFile, "$TDUUPDATE"
    Print #myFile, " 40"
    Print #myFile, "2454598.536862592"
    Print #myFile, "  9"
    Print #myFile, "$TDINDWG"
    Print #myFile, " 40"
    Print #myFile, "0.0006788889"
    Print #myFile, "  9"
    Print #myFile, "$TDUSRTIMER"
    Print #myFile, " 40"
    Print #myFile, "0.0006778819"
    Print #myFile, "  9"
    Print #myFile, "$USRTIMER"
    Print #myFile, " 70"
    Print #myFile, "     1"
    Print #myFile, "  9"
    Print #myFile, "$ANGBASE"
    Print #myFile, " 50"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$ANGDIR"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$PDMODE"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$PDSIZE"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$PLINEWID"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$SPLFRAME"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$SPLINETYPE"
    Print #myFile, " 70"
    Print #myFile, "     6"
    Print #myFile, "  9"
    Print #myFile, "$SPLINESEGS"
    Print #myFile, " 70"
    Print #myFile, "     8"
    Print #myFile, "  9"
    Print #myFile, "$HANDSEED"
    Print #myFile, "  5"
    Print #myFile, "59"
    Print #myFile, "  9"
    Print #myFile, "$SURFTAB1"
    Print #myFile, " 70"
    Print #myFile, "     6"
    Print #myFile, "  9"
    Print #myFile, "$SURFTAB2"
    Print #myFile, " 70"
    Print #myFile, "     6"
    Print #myFile, "  9"
    Print #myFile, "$SURFTYPE"
    Print #myFile, " 70"
    Print #myFile, "     6"
    Print #myFile, "  9"
    Print #myFile, "$SURFU"
    Print #myFile, " 70"
    Print #myFile, "     6"
    Print #myFile, "  9"
    Print #myFile, "$SURFV"
    Print #myFile, " 70"
    Print #myFile, "     6"
    Print #myFile, "  9"
    Print #myFile, "$UCSBASE"
    Print #myFile, "  2"
    Print #myFile, ""
    Print #myFile, "  9"
    Print #myFile, "$UCSNAME"
    Print #myFile, "  2"
    Print #myFile, ""
    Print #myFile, "  9"
    Print #myFile, "$UCSORG"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$UCSXDIR"
    Print #myFile, " 10"
    Print #myFile, "1.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$UCSYDIR"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "1.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$UCSORTHOREF"
    Print #myFile, "  2"
    Print #myFile, ""
    Print #myFile, "  9"
    Print #myFile, "$UCSORTHOVIEW"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$UCSORGTOP"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$UCSORGBOTTOM"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$UCSORGLEFT"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$UCSORGRIGHT"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$UCSORGFRONT"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$UCSORGBACK"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$PUCSBASE"
    Print #myFile, "  2"
    Print #myFile, ""
    Print #myFile, "  9"
    Print #myFile, "$PUCSNAME"
    Print #myFile, "  2"
    Print #myFile, ""
    Print #myFile, "  9"
    Print #myFile, "$PUCSORG"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$PUCSXDIR"
    Print #myFile, " 10"
    Print #myFile, "1.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$PUCSYDIR"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "1.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$PUCSORTHOREF"
    Print #myFile, "  2"
    Print #myFile, ""
    Print #myFile, "  9"
    Print #myFile, "$PUCSORTHOVIEW"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$PUCSORGTOP"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$PUCSORGBOTTOM"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$PUCSORGLEFT"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$PUCSORGRIGHT"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$PUCSORGFRONT"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$PUCSORGBACK"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$USERI1"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$USERI2"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$USERI3"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$USERI4"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$USERI5"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$USERR1"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$USERR2"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$USERR3"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$USERR4"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$USERR5"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$WORLDVIEW"
    Print #myFile, " 70"
    Print #myFile, "     1"
    Print #myFile, "  9"
    Print #myFile, "$SHADEDGE"
    Print #myFile, " 70"
    Print #myFile, "     3"
    Print #myFile, "  9"
    Print #myFile, "$SHADEDIF"
    Print #myFile, " 70"
    Print #myFile, "    70"
    Print #myFile, "  9"
    Print #myFile, "$TILEMODE"
    Print #myFile, " 70"
    Print #myFile, "     1"
    Print #myFile, "  9"
    Print #myFile, "$MAXACTVP"
    Print #myFile, " 70"
    Print #myFile, "    64"
    Print #myFile, "  9"
    Print #myFile, "$PINSBASE"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$PLIMCHECK"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$PEXTMIN"
    Print #myFile, " 10"
    Print #myFile, "1.000000000000000E+20"
    Print #myFile, " 20"
    Print #myFile, "1.000000000000000E+20"
    Print #myFile, " 30"
    Print #myFile, "1.000000000000000E+20"
    Print #myFile, "  9"
    Print #myFile, "$PEXTMAX"
    Print #myFile, " 10"
    Print #myFile, "-1.000000000000000E+20"
    Print #myFile, " 20"
    Print #myFile, "-1.000000000000000E+20"
    Print #myFile, " 30"
    Print #myFile, "-1.000000000000000E+20"
    Print #myFile, "  9"
    Print #myFile, "$PLIMMIN"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$PLIMMAX"
    Print #myFile, " 10"
    Print #myFile, "420.0"
    Print #myFile, " 20"
    Print #myFile, "297.0"
    Print #myFile, "  9"
    Print #myFile, "$UNITMODE"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$VISRETAIN"
    Print #myFile, " 70"
    Print #myFile, "     1"
    Print #myFile, "  9"
    Print #myFile, "$PLINEGEN"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$PSLTSCALE"
    Print #myFile, " 70"
    Print #myFile, "     1"
    Print #myFile, "  9"
    Print #myFile, "$TREEDEPTH"
    Print #myFile, " 70"
    Print #myFile, "  3020"
    Print #myFile, "  9"
    Print #myFile, "$CMLSTYLE"
    Print #myFile, "  2"
    Print #myFile, "Standard"
    Print #myFile, "  9"
    Print #myFile, "$CMLJUST"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$CMLSCALE"
    Print #myFile, " 40"
    Print #myFile, "20.0"
    Print #myFile, "  9"
    Print #myFile, "$PROXYGRAPHICS"
    Print #myFile, " 70"
    Print #myFile, "     1"
    Print #myFile, "  9"
    Print #myFile, "$MEASUREMENT"
    Print #myFile, " 70"
    Print #myFile, "     1"
    Print #myFile, "  9"
    Print #myFile, "$CELWEIGHT"
    Print #myFile, "370"
    Print #myFile, "    -1"
    Print #myFile, "  9"
    Print #myFile, "$ENDCAPS"
    Print #myFile, "280"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$JOINSTYLE"
    Print #myFile, "280"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$LWDISPLAY"
    Print #myFile, "290"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$INSUNITS"
    Print #myFile, " 70"
    Print #myFile, "     4"
    Print #myFile, "  9"
    Print #myFile, "$HYPERLINKBASE"
    Print #myFile, "  1"
    Print #myFile, ""
    Print #myFile, "  9"
    Print #myFile, "$STYLESHEET"
    Print #myFile, "  1"
    Print #myFile, ""
    Print #myFile, "  9"
    Print #myFile, "$XEDIT"
    Print #myFile, "290"
    Print #myFile, "     1"
    Print #myFile, "  9"
    Print #myFile, "$CEPSNTYPE"
    Print #myFile, "380"
    Print #myFile, "     0"
    Print #myFile, "  9"
    Print #myFile, "$PSTYLEMODE"
    Print #myFile, "290"
    Print #myFile, "     1"
    Print #myFile, "  9"
    Print #myFile, "$FINGERPRINTGUID"
    Print #myFile, "  2"
    Print #myFile, "{FDEAD578-A652-11D2-9A35-0060089B3A3F}"
    Print #myFile, "  9"
    Print #myFile, "$VERSIONGUID"
    Print #myFile, "  2"
    Print #myFile, "{32691AAC-1F59-11DD-3286-0002449A8F44}"
    Print #myFile, "  9"
    Print #myFile, "$EXTNAMES"
    Print #myFile, "290"
    Print #myFile, "     1"
    Print #myFile, "  9"
    Print #myFile, "$PSVPSCALE"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  9"
    Print #myFile, "$OLESTARTUP"
    Print #myFile, "290"
    Print #myFile, "     0"
    Print #myFile, "  0"
    Print #myFile, "ENDSEC"
    Print #myFile, "  0"
    Print #myFile, "SECTION"
    Print #myFile, "  2"
    Print #myFile, "CLASSES"
    Print #myFile, "  0"
    Print #myFile, "CLASS"
    Print #myFile, "  1"
    Print #myFile, "ACDBDICTIONARYWDFLT"
    Print #myFile, "  2"
    Print #myFile, "AcDbDictionaryWithDefault"
    Print #myFile, "  3"
    Print #myFile, "AutoCAD 2000"
    Print #myFile, " 90"
    Print #myFile, "        0"
    Print #myFile, "280"
    Print #myFile, "     0"
    Print #myFile, "281"
    Print #myFile, "     0"
    Print #myFile, "  0"
    Print #myFile, "CLASS"
    Print #myFile, "  1"
    Print #myFile, "ACDBPLACEHOLDER"
    Print #myFile, "  2"
    Print #myFile, "AcDbPlaceHolder"
    Print #myFile, "  3"
    Print #myFile, "AutoCAD 2000"
    Print #myFile, " 90"
    Print #myFile, "        0"
    Print #myFile, "280"
    Print #myFile, "     0"
    Print #myFile, "281"
    Print #myFile, "     0"
    Print #myFile, "  0"
    Print #myFile, "CLASS"
    Print #myFile, "  1"
    Print #myFile, "LAYOUT"
    Print #myFile, "  2"
    Print #myFile, "AcDbLayout"
    Print #myFile, "  3"
    Print #myFile, "AutoCAD 2000"
    Print #myFile, " 90"
    Print #myFile, "        0"
    Print #myFile, "280"
    Print #myFile, "     0"
    Print #myFile, "281"
    Print #myFile, "     0"
    Print #myFile, "  0"
    Print #myFile, "ENDSEC"
    Print #myFile, "  0"
    Print #myFile, "SECTION"
    Print #myFile, "  2"
    Print #myFile, "TABLES"
    Print #myFile, "  0"
    Print #myFile, "TABLE"
    Print #myFile, "  2"
    Print #myFile, "VPORT"
    Print #myFile, "  5"
    Print #myFile, "8"
    Print #myFile, "330"
    Print #myFile, "0"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTable"
    Print #myFile, " 70"
    Print #myFile, "     2"
    Print #myFile, "  0"
    Print #myFile, "VPORT"
    Print #myFile, "  5"
    Print #myFile, "58"
    Print #myFile, "330"
    Print #myFile, "8"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTableRecord"
    Print #myFile, "100"
    Print #myFile, "AcDbViewportTableRecord"
    Print #myFile, "  2"
    Print #myFile, "*Active"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 11"
    Print #myFile, "1.0"
    Print #myFile, " 21"
    Print #myFile, "1.0"
    Print #myFile, " 12"
    Print #myFile, "372.5731632106144"
    Print #myFile, " 22"
    Print #myFile, "260.4854742786073"
    Print #myFile, " 13"
    Print #myFile, "0.0"
    Print #myFile, " 23"
    Print #myFile, "0.0"
    Print #myFile, " 14"
    Print #myFile, "10.0"
    Print #myFile, " 24"
    Print #myFile, "10.0"
    Print #myFile, " 15"
    Print #myFile, "10.0"
    Print #myFile, " 25"
    Print #myFile, "10.0"
    Print #myFile, " 16"
    Print #myFile, "0.0"
    Print #myFile, " 26"
    Print #myFile, "0.0"
    Print #myFile, " 36"
    Print #myFile, "1.0"
    Print #myFile, " 17"
    Print #myFile, "0.0"
    Print #myFile, " 27"
    Print #myFile, "0.0"
    Print #myFile, " 37"
    Print #myFile, "0.0"
    Print #myFile, " 40"
    Print #myFile, "520.9709485572151"
    Print #myFile, " 41"
    Print #myFile, "1.43030303030303"
    Print #myFile, " 42"
    Print #myFile, "50.0"
    Print #myFile, " 43"
    Print #myFile, "0.0"
    Print #myFile, " 44"
    Print #myFile, "0.0"
    Print #myFile, " 50"
    Print #myFile, "0.0"
    Print #myFile, " 51"
    Print #myFile, "0.0"
    Print #myFile, " 71"
    Print #myFile, "     0"
    Print #myFile, " 72"
    Print #myFile, "   100"
    Print #myFile, " 73"
    Print #myFile, "     1"
    Print #myFile, " 74"
    Print #myFile, "     3"
    Print #myFile, " 75"
    Print #myFile, "     0"
    Print #myFile, " 76"
    Print #myFile, "     0"
    Print #myFile, " 77"
    Print #myFile, "     0"
    Print #myFile, " 78"
    Print #myFile, "     0"
    Print #myFile, "281"
    Print #myFile, "     0"
    Print #myFile, " 65"
    Print #myFile, "     1"
    Print #myFile, "110"
    Print #myFile, "0.0"
    Print #myFile, "120"
    Print #myFile, "0.0"
    Print #myFile, "130"
    Print #myFile, "0.0"
    Print #myFile, "111"
    Print #myFile, "1.0"
    Print #myFile, "121"
    Print #myFile, "0.0"
    Print #myFile, "131"
    Print #myFile, "0.0"
    Print #myFile, "112"
    Print #myFile, "0.0"
    Print #myFile, "122"
    Print #myFile, "1.0"
    Print #myFile, "132"
    Print #myFile, "0.0"
    Print #myFile, " 79"
    Print #myFile, "     0"
    Print #myFile, "146"
    Print #myFile, "0.0"
    Print #myFile, "  0"
    Print #myFile, "ENDTAB"
    Print #myFile, "  0"
    Print #myFile, "TABLE"
    Print #myFile, "  2"
    Print #myFile, "LTYPE"
    Print #myFile, "  5"
    Print #myFile, "5"
    Print #myFile, "330"
    Print #myFile, "0"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTable"
    Print #myFile, " 70"
    Print #myFile, "     1"
    Print #myFile, "  0"
    Print #myFile, "LTYPE"
    Print #myFile, "  5"
    Print #myFile, "14"
    Print #myFile, "330"
    Print #myFile, "5"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTableRecord"
    Print #myFile, "100"
    Print #myFile, "AcDbLinetypeTableRecord"
    Print #myFile, "  2"
    Print #myFile, "ByBlock"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  3"
    Print #myFile, ""
    Print #myFile, " 72"
    Print #myFile, "    65"
    Print #myFile, " 73"
    Print #myFile, "     0"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  0"
    Print #myFile, "LTYPE"
    Print #myFile, "  5"
    Print #myFile, "15"
    Print #myFile, "330"
    Print #myFile, "5"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTableRecord"
    Print #myFile, "100"
    Print #myFile, "AcDbLinetypeTableRecord"
    Print #myFile, "  2"
    Print #myFile, "ByLayer"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  3"
    Print #myFile, ""
    Print #myFile, " 72"
    Print #myFile, "    65"
    Print #myFile, " 73"
    Print #myFile, "     0"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  0"
    Print #myFile, "LTYPE"
    Print #myFile, "  5"
    Print #myFile, "16"
    Print #myFile, "330"
    Print #myFile, "5"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTableRecord"
    Print #myFile, "100"
    Print #myFile, "AcDbLinetypeTableRecord"
    Print #myFile, "  2"
    Print #myFile, "CONTINUOUS"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  3"
    Print #myFile, "Solid line"
    Print #myFile, " 72"
    Print #myFile, "    65"
    Print #myFile, " 73"
    Print #myFile, "     0"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, "  0"
    Print #myFile, "LTYPE"
    Print #myFile, "  5"
    Print #myFile, "31"
    Print #myFile, "330"
    Print #myFile, "5"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTableRecord"
    Print #myFile, "100"
    Print #myFile, "AcDbLinetypeTableRecord"
    Print #myFile, "  2"
    Print #myFile, "DOT"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  3"
    Print #myFile, "Dot . . . . . . . . . . . . . . . . . . . . . ."
    Print #myFile, " 72"
    Print #myFile, "    65"
    Print #myFile, " 73"
    Print #myFile, "     2"
    Print #myFile, " 40"
    Print #myFile, "6.349999999999999"
    Print #myFile, " 49"
    Print #myFile, "0.0"
    Print #myFile, " 74"
    Print #myFile, "     0"
    Print #myFile, " 49"
    Print #myFile, "-6.349999999999999"
    Print #myFile, " 74"
    Print #myFile, "     0"
    Print #myFile, "  0"
    Print #myFile, "LTYPE"
    Print #myFile, "  5"
    Print #myFile, "34"
    Print #myFile, "330"
    Print #myFile, "5"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTableRecord"
    Print #myFile, "100"
    Print #myFile, "AcDbLinetypeTableRecord"
    Print #myFile, "  2"
    Print #myFile, "DASHED"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  3"
    Print #myFile, "Dashed __ __ __ __ __ __ __ __ __ __ __ __ __ _"
    Print #myFile, " 72"
    Print #myFile, "    65"
    Print #myFile, " 73"
    Print #myFile, "     2"
    Print #myFile, " 40"
    Print #myFile, "19.05"
    Print #myFile, " 49"
    Print #myFile, "12.7"
    Print #myFile, " 74"
    Print #myFile, "     0"
    Print #myFile, " 49"
    Print #myFile, "-6.349999999999999"
    Print #myFile, " 74"
    Print #myFile, "     0"
    Print #myFile, "  0"
    Print #myFile, "LTYPE"
    Print #myFile, "  5"
    Print #myFile, "35"
    Print #myFile, "330"
    Print #myFile, "5"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTableRecord"
    Print #myFile, "100"
    Print #myFile, "AcDbLinetypeTableRecord"
    Print #myFile, "  2"
    Print #myFile, "DASHED2"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  3"
    Print #myFile, "Dashed (.5x) _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _"
    Print #myFile, " 72"
    Print #myFile, "    65"
    Print #myFile, " 73"
    Print #myFile, "     2"
    Print #myFile, " 40"
    Print #myFile, "9.525"
    Print #myFile, " 49"
    Print #myFile, "6.349999999999999"
    Print #myFile, " 74"
    Print #myFile, "     0"
    Print #myFile, " 49"
    Print #myFile, "-3.174999999999999"
    Print #myFile, " 74"
    Print #myFile, "     0"
    Print #myFile, "  0"
    Print #myFile, "LTYPE"
    Print #myFile, "  5"
    Print #myFile, "37"
    Print #myFile, "330"
    Print #myFile, "5"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTableRecord"
    Print #myFile, "100"
    Print #myFile, "AcDbLinetypeTableRecord"
    Print #myFile, "  2"
    Print #myFile, "DASHDOT"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  3"
    Print #myFile, "Dash dot __ . __ . __ . __ . __ . __ . __ . __"
    Print #myFile, " 72"
    Print #myFile, "    65"
    Print #myFile, " 73"
    Print #myFile, "     4"
    Print #myFile, " 40"
    Print #myFile, "25.4"
    Print #myFile, " 49"
    Print #myFile, "12.7"
    Print #myFile, " 74"
    Print #myFile, "     0"
    Print #myFile, " 49"
    Print #myFile, "-6.349999999999999"
    Print #myFile, " 74"
    Print #myFile, "     0"
    Print #myFile, " 49"
    Print #myFile, "0.0"
    Print #myFile, " 74"
    Print #myFile, "     0"
    Print #myFile, " 49"
    Print #myFile, "-6.349999999999999"
    Print #myFile, " 74"
    Print #myFile, "     0"
    Print #myFile, "  0"
    Print #myFile, "LTYPE"
    Print #myFile, "  5"
    Print #myFile, "3A"
    Print #myFile, "330"
    Print #myFile, "5"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTableRecord"
    Print #myFile, "100"
    Print #myFile, "AcDbLinetypeTableRecord"
    Print #myFile, "  2"
    Print #myFile, "DIVIDE"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  3"
    Print #myFile, "Divide ____ . . ____ . . ____ . . ____ . . ____"
    Print #myFile, " 72"
    Print #myFile, "    65"
    Print #myFile, " 73"
    Print #myFile, "     6"
    Print #myFile, " 40"
    Print #myFile, "31.75"
    Print #myFile, " 49"
    Print #myFile, "12.7"
    Print #myFile, " 74"
    Print #myFile, "     0"
    Print #myFile, " 49"
    Print #myFile, "-6.349999999999999"
    Print #myFile, " 74"
    Print #myFile, "     0"
    Print #myFile, " 49"
    Print #myFile, "0.0"
    Print #myFile, " 74"
    Print #myFile, "     0"
    Print #myFile, " 49"
    Print #myFile, "-6.349999999999999"
    Print #myFile, " 74"
    Print #myFile, "     0"
    Print #myFile, " 49"
    Print #myFile, "0.0"
    Print #myFile, " 74"
    Print #myFile, "     0"
    Print #myFile, " 49"
    Print #myFile, "-6.349999999999999"
    Print #myFile, " 74"
    Print #myFile, "     0"
    Print #myFile, "  0"
    Print #myFile, "LTYPE"
    Print #myFile, "  5"
    Print #myFile, "3D"
    Print #myFile, "330"
    Print #myFile, "5"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTableRecord"
    Print #myFile, "100"
    Print #myFile, "AcDbLinetypeTableRecord"
    Print #myFile, "  2"
    Print #myFile, "CENTER"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  3"
    Print #myFile, "Center ____ _ ____ _ ____ _ ____ _ ____ _ ____"
    Print #myFile, " 72"
    Print #myFile, "    65"
    Print #myFile, " 73"
    Print #myFile, "     4"
    Print #myFile, " 40"
    Print #myFile, "50.8"
    Print #myFile, " 49"
    Print #myFile, "31.75"
    Print #myFile, " 74"
    Print #myFile, "     0"
    Print #myFile, " 49"
    Print #myFile, "-6.349999999999999"
    Print #myFile, " 74"
    Print #myFile, "     0"
    Print #myFile, " 49"
    Print #myFile, "6.349999999999999"
    Print #myFile, " 74"
    Print #myFile, "     0"
    Print #myFile, " 49"
    Print #myFile, "-6.349999999999999"
    Print #myFile, " 74"
    Print #myFile, "     0"
    Print #myFile, "  0"
    Print #myFile, "ENDTAB"
    Print #myFile, "  0"
    Print #myFile, "TABLE"
    Print #myFile, "  2"
    Print #myFile, "LAYER"
    Print #myFile, "  5"
    Print #myFile, "2"
    Print #myFile, "330"
    Print #myFile, "0"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTable"
    Print #myFile, " 70"
    Print #myFile, "     1"
    Print #myFile, "  0"
    Print #myFile, "LAYER"
    Print #myFile, "  5"
    Print #myFile, "10"
    Print #myFile, "330"
    Print #myFile, "2"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTableRecord"
    Print #myFile, "100"
    Print #myFile, "AcDbLayerTableRecord"
    Print #myFile, "  2"
    Print #myFile, "0"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, " 62"
    Print #myFile, "     7"
    Print #myFile, "  6"
    Print #myFile, "CONTINUOUS"
    Print #myFile, "370"
    Print #myFile, "     0"
    Print #myFile, "390"
    Print #myFile, "F"
    Print #myFile, "  0"
    ketmen
    Print #myFile, "ENDTAB"
    Print #myFile, "  0"
    Print #myFile, "TABLE"
    Print #myFile, "  2"
    Print #myFile, "STYLE"
    Print #myFile, "  5"
    Print #myFile, "3"
    Print #myFile, "330"
    Print #myFile, "0"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTable"
    Print #myFile, " 70"
    Print #myFile, "     1"
    Print #myFile, "  0"
    Print #myFile, "STYLE"
    Print #myFile, "  5"
    Print #myFile, "11"
    Print #myFile, "330"
    Print #myFile, "3"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTableRecord"
    Print #myFile, "100"
    Print #myFile, "AcDbTextStyleTableRecord"
    Print #myFile, "  2"
    Print #myFile, "Standard"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, " 41"
    Print #myFile, "1.0"
    Print #myFile, " 50"
    Print #myFile, "0.0"
    Print #myFile, " 71"
    Print #myFile, "     0"
    Print #myFile, " 42"
    Print #myFile, "2.5"
    Print #myFile, "  3"
    Print #myFile, "txt"
    Print #myFile, "  4"
    Print #myFile, ""
    Print #myFile, "  0"
    Print #myFile, "ENDTAB"
    Print #myFile, "  0"
    Print #myFile, "TABLE"
    Print #myFile, "  2"
    Print #myFile, "VIEW"
    Print #myFile, "  5"
    Print #myFile, "6"
    Print #myFile, "330"
    Print #myFile, "0"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTable"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  0"
    Print #myFile, "ENDTAB"
    Print #myFile, "  0"
    Print #myFile, "TABLE"
    Print #myFile, "  2"
    Print #myFile, "UCS"
    Print #myFile, "  5"
    Print #myFile, "7"
    Print #myFile, "330"
    Print #myFile, "0"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTable"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  0"
    Print #myFile, "ENDTAB"
    Print #myFile, "  0"
    Print #myFile, "TABLE"
    Print #myFile, "  2"
    Print #myFile, "APPID"
    Print #myFile, "  5"
    Print #myFile, "2C"
    Print #myFile, "330"
    Print #myFile, "0"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTable"
    Print #myFile, " 70"
    Print #myFile, "     1"
    Print #myFile, "  0"
    Print #myFile, "APPID"
    Print #myFile, "  5"
    Print #myFile, "12"
    Print #myFile, "330"
    Print #myFile, "9"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTableRecord"
    Print #myFile, "100"
    Print #myFile, "AcDbRegAppTableRecord"
    Print #myFile, "  2"
    Print #myFile, "ACAD"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  0"
    Print #myFile, "ENDTAB"
    Print #myFile, "  0"
    Print #myFile, "TABLE"
    Print #myFile, "  2"
    Print #myFile, "DIMSTYLE"
    Print #myFile, "  5"
    Print #myFile, "A"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTable"
    Print #myFile, " 70"
    Print #myFile, "1"
    Print #myFile, "100"
    Print #myFile, "AcDbDimStyleTable"
    Print #myFile, " 71"
    Print #myFile, "0"
    Print #myFile, "  0"
    Print #myFile, "DIMSTYLE"
    Print #myFile, "105"
    Print #myFile, "27"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTableRecord"
    Print #myFile, "100"
    Print #myFile, "AcDbDimStyleTableRecord"
    Print #myFile, "  2"
    Print #myFile, "Standard"
    Print #myFile, " 41"
    Print #myFile, "2.5"
    Print #myFile, " 42"
    Print #myFile, "0.625"
    Print #myFile, " 43"
    Print #myFile, "3.75"
    Print #myFile, " 44"
    Print #myFile, "1.25"
    Print #myFile, " 70"
    Print #myFile, "0"
    Print #myFile, " 73"
    Print #myFile, "0"
    Print #myFile, " 74"
    Print #myFile, "0"
    Print #myFile, " 77"
    Print #myFile, "1"
    Print #myFile, " 78"
    Print #myFile, "8"
    Print #myFile, "140"
    Print #myFile, "2.5"
    Print #myFile, "141"
    Print #myFile, "2.5"
    Print #myFile, "143"
    Print #myFile, "0.03937007874016"
    Print #myFile, "147"
    Print #myFile, "0.625"
    Print #myFile, "171"
    Print #myFile, "3"
    Print #myFile, "172"
    Print #myFile, "1"
    Print #myFile, "271"
    Print #myFile, "2"
    Print #myFile, "272"
    Print #myFile, "2"
    Print #myFile, "274"
    Print #myFile, "3"
    Print #myFile, "278"
    Print #myFile, "44"
    Print #myFile, "283"
    Print #myFile, "0"
    Print #myFile, "284"
    Print #myFile, "8"
    Print #myFile, "340"
    Print #myFile, "11"
    Print #myFile, "  0"
    Print #myFile, "ENDTAB"
    Print #myFile, "  0"
    Print #myFile, "TABLE"
    Print #myFile, "  2"
    Print #myFile, "BLOCK_RECORD"
    Print #myFile, "  5"
    Print #myFile, "1"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTable"
    Print #myFile, " 70"
    Print #myFile, "1"
    Print #myFile, "  0"
    Print #myFile, "BLOCK_RECORD"
    Print #myFile, "  5"
    Print #myFile, "1F"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTableRecord"
    Print #myFile, "100"
    Print #myFile, "AcDbBlockTableRecord"
    Print #myFile, "  2"
    Print #myFile, "*Model_Space"
    Print #myFile, "340"
    Print #myFile, "22"
    Print #myFile, "  0"
    Print #myFile, "BLOCK_RECORD"
    Print #myFile, "  5"
    Print #myFile, "1B"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTableRecord"
    Print #myFile, "100"
    Print #myFile, "AcDbBlockTableRecord"
    Print #myFile, "  2"
    Print #myFile, "*Paper_Space"
    Print #myFile, "340"
    Print #myFile, "1E"
    Print #myFile, "  0"
    Print #myFile, "BLOCK_RECORD"
    Print #myFile, "  5"
    Print #myFile, "23"
    Print #myFile, "100"
    Print #myFile, "AcDbSymbolTableRecord"
    Print #myFile, "100"
    Print #myFile, "AcDbBlockTableRecord"
    Print #myFile, "  2"
    Print #myFile, "*Paper_Space0"
    Print #myFile, "340"
    Print #myFile, "26"
    Print #myFile, "  0"
    Return

End

Sub nbv()

    Print #myFile, "ENDTAB"
    Print #myFile, "  0"
    Print #myFile, "ENDSEC"
    Print #myFile, "  0"
    Print #myFile, "SECTION"
    Print #myFile, "  2"
    Print #myFile, "BLOCKS"
    Print #myFile, "  0"
    Print #myFile, "BLOCK"
    Print #myFile, "  5"
    Print #myFile, "20"
    Print #myFile, "330"
    Print #myFile, "1F"
    Print #myFile, "100"
    Print #myFile, "AcDbEntity"
    Print #myFile, "  8"
    Print #myFile, "0"
    Print #myFile, "100"
    Print #myFile, "AcDbBlockBegin"
    Print #myFile, "  2"
    Print #myFile, "*Model_Space"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  3"
    Print #myFile, "*Model_Space"
    Print #myFile, "  1"
    Print #myFile, ""
    Print #myFile, "  0"
    Print #myFile, "ENDBLK"
    Print #myFile, "  5"
    Print #myFile, "21"
    Print #myFile, "330"
    Print #myFile, "1F"
    Print #myFile, "100"
    Print #myFile, "AcDbEntity"
    Print #myFile, "  8"
    Print #myFile, "0"
    Print #myFile, "100"
    Print #myFile, "AcDbBlockEnd"
    Print #myFile, "  0"
    Print #myFile, "BLOCK"
    Print #myFile, "  5"
    Print #myFile, "1C"
    Print #myFile, "330"
    Print #myFile, "1B"
    Print #myFile, "100"
    Print #myFile, "AcDbEntity"
    Print #myFile, " 67"
    Print #myFile, "     1"
    Print #myFile, "  8"
    Print #myFile, "0"
    Print #myFile, "100"
    Print #myFile, "AcDbBlockBegin"
    Print #myFile, "  2"
    Print #myFile, "*Paper_Space"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  3"
    Print #myFile, "*Paper_Space"
    Print #myFile, "  1"
    Print #myFile, ""
    Print #myFile, "  0"
    Print #myFile, "ENDBLK"
    Print #myFile, "  5"
    Print #myFile, "1D"
    Print #myFile, "330"
    Print #myFile, "1B"
    Print #myFile, "100"
    Print #myFile, "AcDbEntity"
    Print #myFile, " 67"
    Print #myFile, "     1"
    Print #myFile, "  8"
    Print #myFile, "0"
    Print #myFile, "100"
    Print #myFile, "AcDbBlockEnd"
    Print #myFile, "  0"
    Print #myFile, "BLOCK"
    Print #myFile, "  5"
    Print #myFile, "24"
    Print #myFile, "330"
    Print #myFile, "23"
    Print #myFile, "100"
    Print #myFile, "AcDbEntity"
    Print #myFile, "  8"
    Print #myFile, "0"
    Print #myFile, "100"
    Print #myFile, "AcDbBlockBegin"
    Print #myFile, "  2"
    Print #myFile, "*Paper_Space0"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 30"
    Print #myFile, "0.0"
    Print #myFile, "  3"
    Print #myFile, "*Paper_Space0"
    Print #myFile, "  1"
    Print #myFile, ""
    Print #myFile, "  0"
    Print #myFile, "ENDBLK"
    Print #myFile, "  5"
    Print #myFile, "25"
    Print #myFile, "100"
    Print #myFile, "AcDbEntity"
    Print #myFile, "  8"
    Print #myFile, "0"
    Print #myFile, "100"
    Print #myFile, "AcDbBlockEnd"
    Print #myFile, "  0"
    Return

End

Sub son()

    Print #myFile, "ENDSEC"
    Print #myFile, "  0"
    Print #myFile, "SECTION"
    Print #myFile, "  2"
    Print #myFile, "OBJECTS"
    Print #myFile, "  0"
    Print #myFile, "DICTIONARY"
    Print #myFile, "  5"
    Print #myFile, "C"
    Print #myFile, "330"
    Print #myFile, "0"
    Print #myFile, "100"
    Print #myFile, "AcDbDictionary"
    Print #myFile, "281"
    Print #myFile, "     1"
    Print #myFile, "  3"
    Print #myFile, "ACAD_GROUP"
    Print #myFile, "350"
    Print #myFile, "D"
    Print #myFile, "  3"
    Print #myFile, "ACAD_LAYOUT"
    Print #myFile, "350"
    Print #myFile, "1A"
    Print #myFile, "  3"
    Print #myFile, "ACAD_MLINESTYLE"
    Print #myFile, "350"
    Print #myFile, "17"
    Print #myFile, "  3"
    Print #myFile, "ACAD_PLOTSETTINGS"
    Print #myFile, "350"
    Print #myFile, "19"
    Print #myFile, "  3"
    Print #myFile, "ACAD_PLOTSTYLENAME"
    Print #myFile, "350"
    Print #myFile, "E"
    Print #myFile, "  0"
    Print #myFile, "DICTIONARY"
    Print #myFile, "  5"
    Print #myFile, "D"
    Print #myFile, "102"
    Print #myFile, "{ACAD_REACTORS"
    Print #myFile, "330"
    Print #myFile, "C"
    Print #myFile, "102"
    Print #myFile, "}"
    Print #myFile, "330"
    Print #myFile, "C"
    Print #myFile, "100"
    Print #myFile, "AcDbDictionary"
    Print #myFile, "281"
    Print #myFile, "     1"
    Print #myFile, "  0"
    Print #myFile, "DICTIONARY"
    Print #myFile, "  5"
    Print #myFile, "1A"
    Print #myFile, "102"
    Print #myFile, "{ACAD_REACTORS"
    Print #myFile, "330"
    Print #myFile, "C"
    Print #myFile, "102"
    Print #myFile, "}"
    Print #myFile, "330"
    Print #myFile, "C"
    Print #myFile, "100"
    Print #myFile, "AcDbDictionary"
    Print #myFile, "281"
    Print #myFile, "     1"
    Print #myFile, "  3"
    Print #myFile, "Layout1"
    Print #myFile, "350"
    Print #myFile, "1E"
    Print #myFile, "  3"
    Print #myFile, "Layout2"
    Print #myFile, "350"
    Print #myFile, "26"
    Print #myFile, "  3"
    Print #myFile, "Model"
    Print #myFile, "350"
    Print #myFile, "22"
    Print #myFile, "  0"
    Print #myFile, "DICTIONARY"
    Print #myFile, "  5"
    Print #myFile, "17"
    Print #myFile, "102"
    Print #myFile, "{ACAD_REACTORS"
    Print #myFile, "330"
    Print #myFile, "C"
    Print #myFile, "102"
    Print #myFile, "}"
    Print #myFile, "330"
    Print #myFile, "C"
    Print #myFile, "100"
    Print #myFile, "AcDbDictionary"
    Print #myFile, "281"
    Print #myFile, "     1"
    Print #myFile, "  3"
    Print #myFile, "Standard"
    Print #myFile, "350"
    Print #myFile, "18"
    Print #myFile, "  0"
    Print #myFile, "DICTIONARY"
    Print #myFile, "  5"
    Print #myFile, "19"
    Print #myFile, "102"
    Print #myFile, "{ACAD_REACTORS"
    Print #myFile, "330"
    Print #myFile, "C"
    Print #myFile, "102"
    Print #myFile, "}"
    Print #myFile, "330"
    Print #myFile, "C"
    Print #myFile, "100"
    Print #myFile, "AcDbDictionary"
    Print #myFile, "281"
    Print #myFile, "     1"
    Print #myFile, "  0"
    Print #myFile, "ACDBDICTIONARYWDFLT"
    Print #myFile, "  5"
    Print #myFile, "E"
    Print #myFile, "102"
    Print #myFile, "{ACAD_REACTORS"
    Print #myFile, "330"
    Print #myFile, "C"
    Print #myFile, "102"
    Print #myFile, "}"
    Print #myFile, "330"
    Print #myFile, "C"
    Print #myFile, "100"
    Print #myFile, "AcDbDictionary"
    Print #myFile, "281"
    Print #myFile, "     1"
    Print #myFile, "  3"
    Print #myFile, "Normal"
    Print #myFile, "350"
    Print #myFile, "F"
    Print #myFile, "100"
    Print #myFile, "AcDbDictionaryWithDefault"
    Print #myFile, "340"
    Print #myFile, "F"
    Print #myFile, "  0"
    Print #myFile, "LAYOUT"
    Print #myFile, "  5"
    Print #myFile, "1E"
    Print #myFile, "102"
    Print #myFile, "{ACAD_REACTORS"
    Print #myFile, "330"
    Print #myFile, "1A"
    Print #myFile, "102"
    Print #myFile, "}"
    Print #myFile, "330"
    Print #myFile, "1A"
    Print #myFile, "100"
    Print #myFile, "AcDbPlotSettings"
    Print #myFile, "  1"
    Print #myFile, ""
    Print #myFile, "  2"
    Print #myFile, ""
    Print #myFile, "  4"
    Print #myFile, ""
    Print #myFile, "  6"
    Print #myFile, ""
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, " 41"
    Print #myFile, "0.0"
    Print #myFile, " 42"
    Print #myFile, "0.0"
    Print #myFile, " 43"
    Print #myFile, "0.0"
    Print #myFile, " 44"
    Print #myFile, "0.0"
    Print #myFile, " 45"
    Print #myFile, "0.0"
    Print #myFile, " 46"
    Print #myFile, "0.0"
    Print #myFile, " 47"
    Print #myFile, "0.0"
    Print #myFile, " 48"
    Print #myFile, "0.0"
    Print #myFile, " 49"
    Print #myFile, "0.0"
    Print #myFile, "140"
    Print #myFile, "0.0"
    Print #myFile, "141"
    Print #myFile, "0.0"
    Print #myFile, "142"
    Print #myFile, "1.0"
    Print #myFile, "143"
    Print #myFile, "1.0"
    Print #myFile, " 70"
    Print #myFile, "   688"
    Print #myFile, " 72"
    Print #myFile, "     0"
    Print #myFile, " 73"
    Print #myFile, "     0"
    Print #myFile, " 74"
    Print #myFile, "     5"
    Print #myFile, "  7"
    Print #myFile, ""
    Print #myFile, " 75"
    Print #myFile, "    16"
    Print #myFile, "147"
    Print #myFile, "1.0"
    Print #myFile, "148"
    Print #myFile, "0.0"
    Print #myFile, "149"
    Print #myFile, "0.0"
    Print #myFile, "100"
    Print #myFile, "AcDbLayout"
    Print #myFile, "  1"
    Print #myFile, "Layout1"
    Print #myFile, " 70"
    Print #myFile, "     1"
    Print #myFile, " 71"
    Print #myFile, "     1"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 11"
    Print #myFile, "420.0"
    Print #myFile, " 21"
    Print #myFile, "297.0"
    Print #myFile, " 12"
    Print #myFile, "0.0"
    Print #myFile, " 22"
    Print #myFile, "0.0"
    Print #myFile, " 32"
    Print #myFile, "0.0"
    Print #myFile, " 14"
    Print #myFile, "1.000000000000000E+20"
    Print #myFile, " 24"
    Print #myFile, "1.000000000000000E+20"
    Print #myFile, " 34"
    Print #myFile, "1.000000000000000E+20"
    Print #myFile, " 15"
    Print #myFile, "-1.000000000000000E+20"
    Print #myFile, " 25"
    Print #myFile, "-1.000000000000000E+20"
    Print #myFile, " 35"
    Print #myFile, "-1.000000000000000E+20"
    Print #myFile, "146"
    Print #myFile, "0.0"
    Print #myFile, " 13"
    Print #myFile, "0.0"
    Print #myFile, " 23"
    Print #myFile, "0.0"
    Print #myFile, " 33"
    Print #myFile, "0.0"
    Print #myFile, " 16"
    Print #myFile, "1.0"
    Print #myFile, " 26"
    Print #myFile, "0.0"
    Print #myFile, " 36"
    Print #myFile, "0.0"
    Print #myFile, " 17"
    Print #myFile, "0.0"
    Print #myFile, " 27"
    Print #myFile, "1.0"
    Print #myFile, " 37"
    Print #myFile, "0.0"
    Print #myFile, " 76"
    Print #myFile, "     0"
    Print #myFile, "330"
    Print #myFile, "1B"
    Print #myFile, "  0"
    Print #myFile, "LAYOUT"
    Print #myFile, "  5"
    Print #myFile, "26"
    Print #myFile, "102"
    Print #myFile, "{ACAD_REACTORS"
    Print #myFile, "330"
    Print #myFile, "1A"
    Print #myFile, "102"
    Print #myFile, "}"
    Print #myFile, "330"
    Print #myFile, "1A"
    Print #myFile, "100"
    Print #myFile, "AcDbPlotSettings"
    Print #myFile, "  1"
    Print #myFile, ""
    Print #myFile, "  2"
    Print #myFile, ""
    Print #myFile, "  4"
    Print #myFile, ""
    Print #myFile, "  6"
    Print #myFile, ""
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, " 41"
    Print #myFile, "0.0"
    Print #myFile, " 42"
    Print #myFile, "0.0"
    Print #myFile, " 43"
    Print #myFile, "0.0"
    Print #myFile, " 44"
    Print #myFile, "0.0"
    Print #myFile, " 45"
    Print #myFile, "0.0"
    Print #myFile, " 46"
    Print #myFile, "0.0"
    Print #myFile, " 47"
    Print #myFile, "0.0"
    Print #myFile, " 48"
    Print #myFile, "0.0"
    Print #myFile, " 49"
    Print #myFile, "0.0"
    Print #myFile, "140"
    Print #myFile, "0.0"
    Print #myFile, "141"
    Print #myFile, "0.0"
    Print #myFile, "142"
    Print #myFile, "1.0"
    Print #myFile, "143"
    Print #myFile, "1.0"
    Print #myFile, " 70"
    Print #myFile, "   688"
    Print #myFile, " 72"
    Print #myFile, "     0"
    Print #myFile, " 73"
    Print #myFile, "     0"
    Print #myFile, " 74"
    Print #myFile, "     5"
    Print #myFile, "  7"
    Print #myFile, ""
    Print #myFile, " 75"
    Print #myFile, "    16"
    Print #myFile, "147"
    Print #myFile, "1.0"
    Print #myFile, "148"
    Print #myFile, "0.0"
    Print #myFile, "149"
    Print #myFile, "0.0"
    Print #myFile, "100"
    Print #myFile, "AcDbLayout"
    Print #myFile, "  1"
    Print #myFile, "Layout2"
    Print #myFile, " 70"
    Print #myFile, "     1"
    Print #myFile, " 71"
    Print #myFile, "     2"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 11"
    Print #myFile, "12.0"
    Print #myFile, " 21"
    Print #myFile, "9.0"
    Print #myFile, " 12"
    Print #myFile, "0.0"
    Print #myFile, " 22"
    Print #myFile, "0.0"
    Print #myFile, " 32"
    Print #myFile, "0.0"
    Print #myFile, " 14"
    Print #myFile, "0.0"
    Print #myFile, " 24"
    Print #myFile, "0.0"
    Print #myFile, " 34"
    Print #myFile, "0.0"
    Print #myFile, " 15"
    Print #myFile, "0.0"
    Print #myFile, " 25"
    Print #myFile, "0.0"
    Print #myFile, " 35"
    Print #myFile, "0.0"
    Print #myFile, "146"
    Print #myFile, "0.0"
    Print #myFile, " 13"
    Print #myFile, "0.0"
    Print #myFile, " 23"
    Print #myFile, "0.0"
    Print #myFile, " 33"
    Print #myFile, "0.0"
    Print #myFile, " 16"
    Print #myFile, "1.0"
    Print #myFile, " 26"
    Print #myFile, "0.0"
    Print #myFile, " 36"
    Print #myFile, "0.0"
    Print #myFile, " 17"
    Print #myFile, "0.0"
    Print #myFile, " 27"
    Print #myFile, "1.0"
    Print #myFile, " 37"
    Print #myFile, "0.0"
    Print #myFile, " 76"
    Print #myFile, "     0"
    Print #myFile, "330"
    Print #myFile, "23"
    Print #myFile, "  0"
    Print #myFile, "LAYOUT"
    Print #myFile, "  5"
    Print #myFile, "22"
    Print #myFile, "102"
    Print #myFile, "{ACAD_REACTORS"
    Print #myFile, "330"
    Print #myFile, "1A"
    Print #myFile, "102"
    Print #myFile, "}"
    Print #myFile, "330"
    Print #myFile, "1A"
    Print #myFile, "100"
    Print #myFile, "AcDbPlotSettings"
    Print #myFile, "  1"
    Print #myFile, ""
    Print #myFile, "  2"
    Print #myFile, ""
    Print #myFile, "  4"
    Print #myFile, ""
    Print #myFile, "  6"
    Print #myFile, ""
    Print #myFile, " 40"
    Print #myFile, "0.0"
    Print #myFile, " 41"
    Print #myFile, "0.0"
    Print #myFile, " 42"
    Print #myFile, "0.0"
    Print #myFile, " 43"
    Print #myFile, "0.0"
    Print #myFile, " 44"
    Print #myFile, "0.0"
    Print #myFile, " 45"
    Print #myFile, "0.0"
    Print #myFile, " 46"
    Print #myFile, "0.0"
    Print #myFile, " 47"
    Print #myFile, "0.0"
    Print #myFile, " 48"
    Print #myFile, "0.0"
    Print #myFile, " 49"
    Print #myFile, "0.0"
    Print #myFile, "140"
    Print #myFile, "0.0"
    Print #myFile, "141"
    Print #myFile, "0.0"
    Print #myFile, "142"
    Print #myFile, "1.0"
    Print #myFile, "143"
    Print #myFile, "1.0"
    Print #myFile, " 70"
    Print #myFile, "  1712"
    Print #myFile, " 72"
    Print #myFile, "     0"
    Print #myFile, " 73"
    Print #myFile, "     0"
    Print #myFile, " 74"
    Print #myFile, "     0"
    Print #myFile, "  7"
    Print #myFile, ""
    Print #myFile, " 75"
    Print #myFile, "     0"
    Print #myFile, "147"
    Print #myFile, "1.0"
    Print #myFile, "148"
    Print #myFile, "0.0"
    Print #myFile, "149"
    Print #myFile, "0.0"
    Print #myFile, "100"
    Print #myFile, "AcDbLayout"
    Print #myFile, "  1"
    Print #myFile, "Model"
    Print #myFile, " 70"
    Print #myFile, "     1"
    Print #myFile, " 71"
    Print #myFile, "     0"
    Print #myFile, " 10"
    Print #myFile, "0.0"
    Print #myFile, " 20"
    Print #myFile, "0.0"
    Print #myFile, " 11"
    Print #myFile, "12.0"
    Print #myFile, " 21"
    Print #myFile, "9.0"
    Print #myFile, " 12"
    Print #myFile, "0.0"
    Print #myFile, " 22"
    Print #myFile, "0.0"
    Print #myFile, " 32"
    Print #myFile, "0.0"
    Print #myFile, " 14"
    Print #myFile, "0.0"
    Print #myFile, " 24"
    Print #myFile, "0.0"
    Print #myFile, " 34"
    Print #myFile, "0.0"
    Print #myFile, " 15"
    Print #myFile, "0.0"
    Print #myFile, " 25"
    Print #myFile, "0.0"
    Print #myFile, " 35"
    Print #myFile, "0.0"
    Print #myFile, "146"
    Print #myFile, "0.0"
    Print #myFile, " 13"
    Print #myFile, "0.0"
    Print #myFile, " 23"
    Print #myFile, "0.0"
    Print #myFile, " 33"
    Print #myFile, "0.0"
    Print #myFile, " 16"
    Print #myFile, "1.0"
    Print #myFile, " 26"
    Print #myFile, "0.0"
    Print #myFile, " 36"
    Print #myFile, "0.0"
    Print #myFile, " 17"
    Print #myFile, "0.0"
    Print #myFile, " 27"
    Print #myFile, "1.0"
    Print #myFile, " 37"
    Print #myFile, "0.0"
    Print #myFile, " 76"
    Print #myFile, "     0"
    Print #myFile, "330"
    Print #myFile, "1F"
    Print #myFile, "  0"
    Print #myFile, "MLINESTYLE"
    Print #myFile, "  5"
    Print #myFile, "18"
    Print #myFile, "102"
    Print #myFile, "{ACAD_REACTORS"
    Print #myFile, "330"
    Print #myFile, "17"
    Print #myFile, "102"
    Print #myFile, "}"
    Print #myFile, "330"
    Print #myFile, "17"
    Print #myFile, "100"
    Print #myFile, "AcDbMlineStyle"
    Print #myFile, "  2"
    Print #myFile, "STANDARD"
    Print #myFile, " 70"
    Print #myFile, "     0"
    Print #myFile, "  3"
    Print #myFile, ""
    Print #myFile, " 62"
    Print #myFile, "   256"
    Print #myFile, " 51"
    Print #myFile, "90.0"
    Print #myFile, " 52"
    Print #myFile, "90.0"
    Print #myFile, " 71"
    Print #myFile, "     2"
    Print #myFile, " 49"
    Print #myFile, "0.5"
    Print #myFile, " 62"
    Print #myFile, "   256"
    Print #myFile, "  6"
    Print #myFile, "BYLAYER"
    Print #myFile, " 49"
    Print #myFile, "-0.5"
    Print #myFile, " 62"
    Print #myFile, "   256"
    Print #myFile, "  6"
    Print #myFile, "BYLAYER"
    Print #myFile, "  0"
    Print #myFile, "ACDBPLACEHOLDER"
    Print #myFile, "  5"
    Print #myFile, "F"
    Print #myFile, "102"
    Print #myFile, "{ACAD_REACTORS"
    Print #myFile, "330"
    Print #myFile, "E"
    Print #myFile, "102"
    Print #myFile, "}"
    Print #myFile, "330"
    Print #myFile, "E"
    Print #myFile, "  0"
    Print #myFile, "ENDSEC"
    Print #myFile, "  0"
    Print #myFile, "EOF"
Catch
    ilk.hatayaz("son " & Error.Text, Error.Where & "--" & Error.code)
Return
End
